# Generated by Django 4.2.5 on 2023-09-29 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200, verbose_name='رنگ')),
                ('size', models.CharField(max_length=200, verbose_name='سایز')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='blogs.productinformation', verbose_name='اطلاعات تکمیلی'),
        ),
    ]
